out_dir: results
metric_best: accuracy
wandb:
  use: False
  project: TRIANGLES
dataset:
  split_mode: sliced
  split: [[0, 30000], [30000, 35000], [40000, 45000]]
  format: PyG-TUDataset
  name: TRIANGLES
  task: graph
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: LapPE
  node_encoder_bn: False
  edge_encoder: False
  edge_encoder_name: LinearEdge
  edge_encoder_bn: False
posenc_RWSE:
  enable: False
  kernel:
    times_func: range(1,21)
  model: Linear
  dim_pe: 28
  raw_norm_type: BatchNorm
posenc_LapPE:
  enable: True
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 16
  model: DeepSet
  dim_pe: 64
  layers: 2
  raw_norm_type: none
pretrained:
  dir: pretrained/triangle-tf-lap
  reset_prediction_head: False
train:
  mode: inference-only
  batch_size: 96
  eval_period: 1
model:
  type: GPSModel
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: add
gt:
  layer_type: None+Transformer  # CustomGatedGCN+Performer
  layers: 6
  n_heads: 4
  dim_hidden: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.0
  attn_dropout: 0.1
  layer_norm: False
  batch_norm: True
gnn:
  head: san_graph
  layers_pre_mp: 0
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  dim_inner: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: gelu
  dropout: 0.0
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.001
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 50
