out_dir: results
metric_best: accuracy
wandb:
  use: False
  project: TRIANGLES
dataset:
  split_mode: sliced
  split: [[0, 30000], [30000, 35000], [35000, 40000]]
  format: PyG-TUDataset
  name: TRIANGLES
  task: graph
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: GraphormerBias
  node_encoder_bn: False
  edge_encoder: False
  edge_encoder_name: LinearEdge
  edge_encoder_bn: False
posenc_GraphormerBias:
  enable: True
  num_spatial_types: 20
  num_in_degrees: 64
  num_out_degrees: 64
pretrained:
  dir: pretrained/triangle-graphormer
  reset_prediction_head: False
train:
  mode: inference-only
  batch_size: 256
  eval_period: 1
model:
  type: Graphormer
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: graph_token
graphormer:
  num_layers: 6
  num_heads: 4
  embed_dim: 72
  dropout: 0.0
  attention_dropout: 0.1
  mlp_dropout: 0.1
  input_dropout: 0.1
gnn:
  head: graphormer_graph
  layers_pre_mp: 0
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  dim_inner: 72  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  clip_grad_norm_value: 5.0
  optimizer: adamW
  weight_decay: 0.01
  base_lr: 0.001
  max_epoch: 1000
  scheduler: polynomial_with_warmup
  num_warmup_epochs: 50
