out_dir: results
metric_best: mae
metric_agg: argmin
accelerator: 'cuda:0'
wandb:
  use: True
  project: CSL
dataset:
  split_mode: cv-stratifiedkfold-5
  format: PyG-GraphCount
  name: Count
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: TypeDictNode
  node_encoder_num_types: 2
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: TypeDictEdge
  edge_encoder_num_types: 5
  edge_encoder_bn: False
  target: 3
posenc_RWSE:
  enable: False
  kernel:
    times_func: range(1,21)
  model: Linear
  dim_pe: 28
  raw_norm_type: BatchNorm
posenc_LapPE:
  enable: False
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 16
  model: DeepSet
  dim_pe: 16
  layers: 2
  raw_norm_type: none
prep:
  exp: False
  exp_deg: 3
  use_exp_edges: False
  add_edge_index: False # Set True if you want to add real edges beside expander edges
  use_local_neighbors: True
  num_virt_node: 0 # Set True if you want to add global node connections beside expander edges
train:
  mode: custom
  batch_size: 256
  eval_period: 1
  enable_ckpt: True  # Checkpointing can now be disabled to save I/O when e.g. just benchmarking.
  ckpt_best: True  # WARNING: Checkpoint every epoch a better model is found may increase I/O significantly.
#  ckpt_period: 100  # Follow set checkpointing schedule
  ensemble_repeat: 1
  ensemble_mode: none
model:
  type: GPSModel
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: add
gt:
  layer_type: None+Transformer  # CustomGatedGCN+Performer
  layers: 3
  n_heads: 4
  dim_hidden: 256  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.0
  attn_dropout: 0.1
  layer_norm: False
  batch_norm: True
gnn:
  head: san_graph
  layers_pre_mp: 0
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  dim_inner: 256  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: gelu
  dropout: 0.0
  agg: mean
  normalize_adj: False
  num_layer_MPNN: 0
  similarity_type: cos
  inference_mode: sample
  mp_threshold: 0.0
  force_undirected: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 1e-3
  max_epoch: 300
  scheduler: cosine_with_warmup
  num_warmup_epochs: 50
  reduce_factor: 0.7
  schedule_patience: 8
  min_lr: 1e-7
