out_dir: results
metric_best: mae
metric_agg: argmin
wandb:
  use: True
  project: peptides-struct
dataset:
  format: OGB
  name: peptides-structural
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: Atom+LapPE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond_custom
  edge_encoder_bn: False
prep:
  exp: False
  exp_deg: 3
  use_exp_edges: False
  add_edge_index: False # Set True if you want to add real edges beside expander edges
  use_local_neighbors: True # Set True if you want to use local neighbor attention
  num_virt_node: 5 # Set True if you want to add global node connections beside expander edges
posenc_LapPE:
  enable: True
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 10
  model: DeepSet
  dim_pe: 16
  layers: 2
  raw_norm_type: none
train:
  mode: custom
  batch_size: 128
  eval_period: 1
  ckpt_period: 100
  ensemble_repeat: 1
  ensemble_mode: none
model:
  type: kSimplicialTransformerSparse
  loss_fun: l1
  graph_pooling: mean
  simplex_pooling: node
gt:
  layer_type: None+Exphormer
  layers: 8
  n_heads: 4
  dim_hidden: 120  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.1
  attn_dropout: 0.5
  layer_norm: False
  batch_norm: True
  tuple_encoder_mode: add
gnn:
  head: san_graph
  layers_pre_mp: 0
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  dim_inner: 120  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.0
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.0005
  max_epoch: 300
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
#optim:
#  optimizer: adamW
#  weight_decay: 0.0
#  base_lr: 0.0003
#  max_epoch: 500
#  scheduler: reduce_on_plateau
#  reduce_factor: 0.5
#  schedule_patience: 20
#  min_lr: 1e-5
